basePath: /api
definitions:
  models.Card:
    properties:
      card_answer:
        example: "42"
        type: string
      card_explication:
        example: The number 42 is the answer to life has written in a very famous
          book
        type: string
      card_format:
        example: Date / Name / Country
        type: string
      card_image:
        type: string
      card_question:
        example: What's the answer to life ?
        type: string
      card_tips:
        example: The answer is from a book
        type: string
      card_type:
        example: int/string
        type: string
      deck_id:
        example: 1
        type: integer
    type: object
host: localhost:1813
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Memnix
  version: "1.0"
paths:
  /v1/cards/id/{id}:
    get:
      description: Get a card by tech id
      parameters:
      - description: Card ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Card'
            type: array
      summary: get a card
      tags:
      - Card
swagger: "2.0"
