basePath: /api
definitions:
  models.Card:
    properties:
      card_answer:
        example: "42"
        type: string
      card_explication:
        example: The number 42 is the answer to life has written in a very famous
          book
        type: string
      card_format:
        example: Date / Name / Country
        type: string
      card_image:
        description: Should be an url
        type: string
      card_question:
        example: What's the answer to life ?
        type: string
      card_tips:
        example: The answer is from a book
        type: string
      card_type:
        example: 0
        type: integer
      deck:
        $ref: '#/definitions/models.Deck'
      deck_id:
        example: 1
        type: integer
    type: object
  models.Deck:
    properties:
      deck_banner:
        example: A banner url
        type: string
      deck_description:
        example: A simple demo deck
        type: string
      deck_name:
        example: First Deck
        type: string
      deck_status:
        description: '1: Draft - 2: Private - 3: Published'
        example: 0
        type: integer
    type: object
  models.Rating:
    properties:
      deck:
        $ref: '#/definitions/models.Deck'
      deck_id:
        example: 1
        type: integer
      user:
        $ref: '#/definitions/models.User'
      user_id:
        example: 1
        type: integer
      value:
        example: 3
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      user_avatar:
        example: avatar url
        type: string
      user_bio:
        example: A simple demo bio
        type: string
      user_name:
        description: This should be unique
        example: Yume
        type: string
      user_permissions:
        description: '0: User; 1: Mod; 2: Admin'
        example: 0
        type: integer
    type: object
host: localhost:1813
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Memnix
  version: "1.0"
paths:
  /v1/cards/:
    get:
      description: Get every cards. Shouldn't really be used
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Card'
            type: array
      summary: get all cards
      tags:
      - Card
  /v1/cards/{deckID}/next:
    get:
      description: Get next card by deckID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Card'
      summary: get a card
      tags:
      - Card
  /v1/cards/deck/{deckID}:
    get:
      description: Get every cards from a deck
      parameters:
      - description: Deck ID
        in: path
        name: deckID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Card'
            type: array
      summary: get a list of card
      tags:
      - Card
  /v1/cards/deck/{deckID}/bulk:
    post:
      consumes:
      - application/json
      description: Create cards
      parameters:
      - description: Cards to create
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/models.Card'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: create cards
      tags:
      - Card
  /v1/cards/id/{id}:
    get:
      description: Get a card by tech id
      parameters:
      - description: Card ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Card'
      summary: get a card
      tags:
      - Card
  /v1/cards/new:
    post:
      consumes:
      - application/json
      description: Create a new card
      parameters:
      - description: Card to create
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/models.Card'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: create a card
      tags:
      - Card
  /v1/cards/next:
    get:
      description: Get next card
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Card'
      summary: get a card
      tags:
      - Card
  /v1/cards/response:
    post:
      consumes:
      - application/json
      description: Post a response and check it
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: post a response
      tags:
      - Card
  /v1/cards/today:
    get:
      description: Get next today card
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Card'
      summary: get a card
      tags:
      - Card
  /v1/decks:
    get:
      description: Get every deck. Shouldn't really be used, consider using /v1/decks/public
        instead !
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Deck'
      summary: get all decks
      tags:
      - Deck
  /v1/decks/{deckID}/edit:
    put:
      consumes:
      - application/json
      description: Edit a deck
      parameters:
      - description: Deck to edit
        in: body
        name: deck
        required: true
        schema:
          $ref: '#/definitions/models.Deck'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: edit a deck
      tags:
      - Deck
  /v1/decks/{deckID}/subscribe:
    post:
      consumes:
      - application/json
      description: Subscribe to a deck
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: sub deck
      tags:
      - Deck
  /v1/decks/{deckID}/unsubscribe:
    post:
      consumes:
      - application/json
      description: Unsubscribe to a deck
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: unsub deck
      tags:
      - Deck
  /v1/decks/{deckID}/users:
    get:
      description: Get all the sub users to a deck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: get a list of users
      tags:
      - Deck
  /v1/decks/{id}:
    get:
      description: Get a deck by tech ID
      parameters:
      - description: Deck ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: model
      summary: get a deck
      tags:
      - Deck
  /v1/decks/available:
    get:
      description: Get all public deck that you are not sub to
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Deck'
            type: array
      summary: get a list of deck
      tags:
      - Deck
  /v1/decks/new:
    post:
      consumes:
      - application/json
      description: Create a new deck
      parameters:
      - description: Deck to create
        in: body
        name: deck
        required: true
        schema:
          $ref: '#/definitions/models.Deck'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: create a deck
      tags:
      - Deck
  /v1/decks/public:
    get:
      description: Get all public deck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Deck'
            type: array
      summary: get a list of deck
      tags:
      - Deck
  /v1/decks/sub:
    get:
      description: Get decks a user is sub to
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Deck'
            type: array
      summary: get a list of deck
      tags:
      - Deck
  /v1/rating/new:
    post:
      consumes:
      - application/json
      description: Rate a deck
      parameters:
      - description: Rating to create or update
        in: body
        name: rating
        required: true
        schema:
          $ref: '#/definitions/models.Rating'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: rate a deck
      tags:
      - Rating
  /v1/ratings:
    get:
      description: Get all ratings. Admin Only
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Rating'
            type: array
      summary: get a list of ratings
      tags:
      - Rating
  /v1/ratings/deck/{deckID}:
    get:
      description: Get all ratings from a deckID. Admin Only
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Rating'
            type: array
      summary: get a list of ratings
      tags:
      - Rating
  /v1/ratings/deck/{deckID}/average:
    get:
      description: Get average rating from a deckID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: get an average rating
      tags:
      - Rating
  /v1/ratings/deck/{deckID}/user:
    get:
      description: Get ratings from a deckID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Rating'
      summary: get a rating
      tags:
      - Rating
  /v1/ratings/deck/{deckID}/user/{userID}:
    get:
      description: Get a rating by user & deck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Rating'
      summary: get a rating
      tags:
      - Rating
  /v1/users:
    get:
      description: Get all users.  Shouldn't really be used
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: get a list of user
      tags:
      - User
  /v1/users/id/{id}:
    get:
      description: Get an user by ID.
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: get an user
      tags:
      - User
swagger: "2.0"
